### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by relecand** [cli-ish/moodle-block_downloaduserlist#1]
# Review
## Test
* Der Code-Checker hat nichts zu beanstanden :thumbsup: 
* Es wurde scheinbar ohne die Developer Debug Ausgabe gearbeitet: es gibt einige Warnungen. Siehe https://docs.moodle.org/dev/Developer_Mode
    * Berechtigung in db/access.php falsch benannt (--> [access.php:26](https://github.com/BlackNetworkBit/moodle-block_downloaduserlist/blob/1a252e069f5825636ac73dd2ccfe623edc8b4b29/db/access.php#L26), --> screenshot 3). siehe https://docs.moodle.org/dev/Access_API
    * deprecated functions (--> screenshot 3)
    * URL zum Download der Datei beachtet ursprünglichen Pfad nicht: testserver.vm/m/stable_31/ wird zu testserver.vm/blocks ... (--> screenshot 4)
    * Viele weitere Warnungen (--> screenshot 1 und 2)

### version.php
* Cron-Eintrag nicht nötig [version.php#L30](https://github.com/BlackNetworkBit/moodle-block_downloaduserlist/blob/1a252e069f5825636ac73dd2ccfe623edc8b4b29/version.php#L30)
* maturity und release fehlt (wird empfohlen)
siehe https://docs.moodle.org/dev/version.php

### block_downloaduserlist.php
* [lock_downloaduserlist.php:67-69](https://github.com/BlackNetworkBit/moodle-block_downloaduserlist/blob/1a252e069f5825636ac73dd2ccfe623edc8b4b29/block_downloaduserlist.php#L67-L69): has_config() wird nicht benötigt, da das Plugin keine Globale config hat
* [block_downloaduserlist.php:71-74](https://github.com/BlackNetworkBit/moodle-block_downloaduserlist/blob/1a252e069f5825636ac73dd2ccfe623edc8b4b29/block_downloaduserlist.php#L71-L74): Platzhalter kann entfernt werden
* [block_downloaduserlist.php:63-65](https://github.com/BlackNetworkBit/moodle-block_downloaduserlist/blob/1a252e069f5825636ac73dd2ccfe623edc8b4b29/block_downloaduserlist.php#L63-L65): Soll das Plugin wirklich mehrfach auf einer Seite angezeigt werden können?
* [block_downloaduserlist.php:49](https://github.com/BlackNetworkBit/moodle-block_downloaduserlist/blob/1a252e069f5825636ac73dd2ccfe623edc8b4b29/block_downloaduserlist.php#L49): lang strings benutzen mit get_string(); siehe https://docs.moodle.org/dev/String_API
* [block_downloaduserlist.php:48](https://github.com/BlackNetworkBit/moodle-block_downloaduserlist/blob/1a252e069f5825636ac73dd2ccfe623edc8b4b29/block_downloaduserlist.php#L48): Moodle's html_writer Methoden benutzen um HTML code zu generieren (html_writer::link()); Moodle's moodle_url Klasse für URLs benutzen

### db/access.php
* [db/access.php:26](https://github.com/BlackNetworkBit/moodle-block_downloaduserlist/blob/1a252e069f5825636ac73dd2ccfe623edc8b4b29/db/access.php#L26): Namensschema für Capabilities beachten (Korrekt: 'block/downloaduserlist:addinstance')

### Sonstiges
* [settings.php]() wird nicht benötigt wenn das Plugin keine globalen Settings hat
* [edit_form.php]() wird nicht benötigt wenn es keine Instanz-spezifischen Einstellungen gibt

## Screenshots

**Screenshot 1**

![downloaduserlist_1](https://cloud.githubusercontent.com/assets/5286499/20109952/9cf9e5f4-a5e2-11e6-9fb6-7c300854a6e2.png)

**Screenshot 2**

![downloaduserlist_2](https://cloud.githubusercontent.com/assets/5286499/20109950/9ce933bc-a5e2-11e6-8561-fa83305f0dee.png)

**Screenshot 3**

![downloaduserlist_3](https://cloud.githubusercontent.com/assets/5286499/20109951/9cecce32-a5e2-11e6-9c74-ce2db97766ca.png)

**Screenshot 4**

![downloaduserlist_4](https://cloud.githubusercontent.com/assets/5286499/20109949/9ce58ed8-a5e2-11e6-991f-af6e30f058c9.png)

# Allgemeine Infos
* https://docs.moodle.org/dev/Developer_Mode
* https://docs.moodle.org/dev/Finding_your_way_into_the_Moodle_code
* https://docs.moodle.org/dev/Blocks
* https://docs.moodle.org/dev/Moodle_IDE

**Comment by cli-ish** [comment]
Alle angegebenen Probleme sollten jetzt gelöst sein.
